### ISSUE TITLE
Login on ig side randomly fails

### ISSUE THREAD

**Issue by awesomemoder316** [jake-walker/instagram-discord-bridge#14]
Sometimes, I get this error after restarting a few times. Is it due to a temporary IP ban and is there a way to get around this? 

```
Unhandled rejection IgLoginRequiredError: GET /api/v1/accounts/current_user/?edit=true - 403 Forbidden; login_required
at Request.handleResponseError (/home/ubuntu/instagram-discord-bridge/node_modules/instagram-private-api/dist/core/request.js:113:24)
at Request.send (/home/ubuntu/instagram-discord-bridge/node_modules/instagram-private-api/dist/core/request.js:53:28)
```

**Comment by jake-walker** [comment]
I haven't used this bot for a while, but I think the only way is to wait a few hours for the temporary ban to disappear. 

You may be able to use multiple proxy servers and randomly route traffic through them to essentially get multiple IP addresses.
