### ISSUE TITLE
error about finding discord channel

### ISSUE THREAD

**Issue by filip2cz** [jake-walker/instagram-discord-bridge#19]
I tested it with multiple channels, 2 on server and also with dms with that bot.

I have this output:
```
ℹ  info      Setting up Instagram...
⬤  debug     Logging into Instagram...
⬤  debug     Trying normal login...
ℹ  info      Setting up Discord...
/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/client/ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/structures/Guild.js:206:68)
    at GuildCreateHandler.handle (/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/tmp/instagram-discord-bridge/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (/root/tmp/instagram-discord-bridge/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
```

**Comment by jake-walker** [comment]
Hi @filip2cz, unfortunately this is a few years old now and is not something I’m actively maintaining. From the error, I imagine discord may have updated their API, in which case updating the dependencies of the project may help.
